// <auto-generated />
using System;
using GeradorUsuario.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeradorUsuario.Infra.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20240514031932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeradorUsuario.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("86a71477-4469-44b2-bbe7-e0bde16ea3d8"),
                            Email = "joao@email.com",
                            NomeUsuario = "João",
                            Senha = "1234"
                        },
                        new
                        {
                            Uuid = new Guid("d311130e-5b3c-4325-b3a0-0cb7bcba916c"),
                            Email = "maria@email.com",
                            NomeUsuario = "Maria",
                            Senha = "5678"
                        },
                        new
                        {
                            Uuid = new Guid("29bd07ff-c2f1-4cf5-ace6-9641a1e875e2"),
                            Email = "jose@email.com",
                            NomeUsuario = "José",
                            Senha = "1234"
                        },
                        new
                        {
                            Uuid = new Guid("57e3bf36-56cd-4fff-8a91-e1b08b461444"),
                            Email = "Ana@email.com",
                            NomeUsuario = "Ana",
                            Senha = "5678"
                        },
                        new
                        {
                            Uuid = new Guid("84eb80ad-ca7f-4443-80f7-a44a7127fc34"),
                            Email = "pedro@email.com",
                            NomeUsuario = "Pedro",
                            Senha = "1234"
                        },
                        new
                        {
                            Uuid = new Guid("aaed7b82-5b79-4ed8-82e4-d0e790e791cd"),
                            Email = "paula@email.com",
                            NomeUsuario = "Paula",
                            Senha = "5678"
                        },
                        new
                        {
                            Uuid = new Guid("9102494e-eae0-4bf7-aada-f1251ab38296"),
                            Email = "carlos@email.com",
                            NomeUsuario = "Carlos",
                            Senha = "1234"
                        },
                        new
                        {
                            Uuid = new Guid("a18dd8ce-b0d3-49b3-ba7e-f9da81a46ed8"),
                            Email = "mariana@email.com",
                            NomeUsuario = "Mariana",
                            Senha = "5678"
                        },
                        new
                        {
                            Uuid = new Guid("8a7007d0-ea74-4e26-a20d-eb90f52763a9"),
                            Email = "lucas@email.com",
                            NomeUsuario = "Lucas",
                            Senha = "1234"
                        },
                        new
                        {
                            Uuid = new Guid("501ab281-194b-458e-af85-1f50d56e0e4b"),
                            Email = "juliana@email.com",
                            NomeUsuario = "Juliana",
                            Senha = "5678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
